addSbtPlugin("org.scalameta"      % "sbt-mdoc"      % "2.8.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "2.4.3")
addSbtPlugin("org.typelevel"      % "sbt-typelevel" % "0.8.4")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.8")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo" % "0.13.1")
