name: Update documentation

on:
  release:
    types: [published]

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Generate documentation
        run: sbt docs/mdoc
      - name: Commit to repository
        env:
          COMMIT_MSG: |
            Update documentation
            skip-checks: true
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout main
          git config user.email "alanartigao@gmail.com"
          git config user.name "aartigao"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push -u origin main)
